exp_name: PVFI-V00-Laper # experiment name

#### data loader
dataset_cfg:
  data_root: "data/gywu-data/vimeo_triplet"
  batch_size: 16 # in total
  nb_data_worker: 8
  of_method:
    - 'raft'
    - 'gmflow'

#### network structures
model_cfg:
  version: v00

### optimizer
optimizer_cfg:
  max_lr: 5.0e-4
  loss: nll+0.1*lap+0.2*per
  epochs: 96

### logger
logger_cfg:
  root: train-logs
  save_interval: 100 # checkpointing rate (steps)
  eval_interval: 500 # validating rate (steps)
